apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: receiver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
        version: v2
    spec:
      containers:
      - name: receiver
        image: allansli/receiver:v2
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "v2"
        ports:
        - containerPort: 50051
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
  strategy:
    canary:
      steps:
        - setWeight: 33
        - pause: {duration: 5m}
        - setWeight: 100
        - pause: {duration: 5m}
---
apiVersion: v1
kind: Service
metadata:
  name: receiver
spec:
  selector:
    app: receiver
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-stable
spec:
  selector:
    app: receiver
    version: v1
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-canary
spec:
  selector:
    app: receiver
    version: v2
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
