apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: capturer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capturer
  template:
    metadata:
      labels:
        app: capturer
    spec:
      containers:
      - name: capturer
        image: allansli/capturer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: capturer
spec:
  selector:
    app: capturer
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080